In [1]:
import pandas as pd

In [2]:
import os
import sys
os.system('which python')
sys.version,sys.executable

/software/miniconda3/envs/zixin/bin/python

/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.

('3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]',
 '/software/miniconda3/envs/zixin/bin/python')

In [ ]:
target_file='./merge'
fam=pd.read_csv('%s/all_without_miss.fam'% target_file  ,sep='\s',header=None)
fam.columns=['#FID','IID','FAID','MOID','SEX','PHENO']

/software/miniconda3/envs/zixin/lib/python3.7/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

In [ ]:
pheno_path='Glucose_withGeno.txt'
pca=pd.read_csv('./pcs_merge_all.txt',sep='\t')
pca.rename({'FID':'#FID'},axis=1,inplace=True)
pheno=pd.read_csv(pheno_path,sep='\t')
pheno.rename({'Glucose':'outcome'},axis=1,inplace=True)
pheno.rename({'FID':'#FID'},axis=1,inplace=True)

In [5]:
pheno

            IID        #FID  na1  na2  na3  pheno1  sex_m1f2   age  outcome
0         OA001       OA001    0    0    0      -9       2.0  75.0     4.80
1         OA002       OA002    0    0    0      -9       2.0  72.0     4.20
2         OA008       OA008    0    0    0      -9       2.0  75.0     5.40
3         OA009       OA009    0    0    0      -9       2.0  69.0     5.00
4         OA010       OA010    0    0    0      -9       1.0  65.0     6.80
..          ...         ...  ...  ...  ...     ...       ...   ...      ...
819  ZQXHNK0329  ZQXHNK0329    0    0    0      -9       2.0  52.0     4.48
820  ZQXHNK0334  ZQXHNK0334    0    0    0      -9       2.0  62.0     5.22
821  ZQXHNK0341  ZQXHNK0341    0    0    0      -9       2.0  63.0     5.44
822  ZQXHNK0343  ZQXHNK0343    0    0    0      -9       1.0  27.0     4.41
823  ZQXHNK0346  ZQXHNK0346    0    0    0      -9       1.0  69.0     5.11

[824 rows x 9 columns]

In [6]:
fam

             #FID          IID  FAID  MOID  SEX  PHENO
0     DL002-ST023  DL002-ST023     0     0    0     -9
1           DL003        DL003     0     0    0     -9
2     DL006-ST027  DL006-ST027     0     0    0     -9
3           DL007        DL007     0     0    0     -9
4           DL009        DL009     0     0    0     -9
...           ...          ...   ...   ...  ...    ...
1419   ZQXHNK0334   ZQXHNK0334     0     0    0     -9
1420   ZQXHNK0339   ZQXHNK0339     0     0    0     -9
1421   ZQXHNK0341   ZQXHNK0341     0     0    0     -9
1422   ZQXHNK0343   ZQXHNK0343     0     0    0     -9
1423   ZQXHNK0346   ZQXHNK0346     0     0    0     -9

[1424 rows x 6 columns]

In [7]:
#all( pd.merge(fam,pheno,how='left')['IID']==fam['IID'] )

In [8]:
fam_pheno=pd.merge(fam,pheno,how='inner')

In [ ]:
fam_pheno=fam_pheno[fam_pheno['outcome']<7]

In [10]:
fam_pheno

,#FID,IID,FAID,MOID,SEX,PHENO,na1,na2,na3,pheno1,sex_m1f2,age,outcome
0,OA001,OA001,0,0,0,-9,0,0,0,-9,2.0,75.0,4.80
1,OA002,OA002,0,0,0,-9,0,0,0,-9,2.0,72.0,4.20
2,OA008,OA008,0,0,0,-9,0,0,0,-9,2.0,75.0,5.40
3,OA009,OA009,0,0,0,-9,0,0,0,-9,2.0,69.0,5.00
4,OA010,OA010,0,0,0,-9,0,0,0,-9,1.0,65.0,6.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,ZQXHNK0329,ZQXHNK0329,0,0,0,-9,0,0,0,-9,2.0,52.0,4.48
820,ZQXHNK0334,ZQXHNK0334,0,0,0,-9,0,0,0,-9,2.0,62.0,5.22
821,ZQXHNK0341,ZQXHNK0341,0,0,0,-9,0,0,0,-9,2.0,63.0,5.44
822,ZQXHNK0343,ZQXHNK0343,0,0,0,-9,0,0,0,-9,1.0,27.0,4.41
823,ZQXHNK0346,ZQXHNK0346,0,0,0,-9,0,0,0,-9,1.0,69.0,5.11

In [11]:
fam_pheno_pca=pd.merge(fam_pheno,pca,how='inner')

In [12]:
fam_pheno_pca

,#FID,IID,FAID,MOID,SEX,PHENO,na1,na2,na3,pheno1,...,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20
0,OA001,OA001,0,0,0,-9,0,0,0,-9,...,0.001640,0.006908,0.003942,0.005487,-0.007080,0.000694,-0.004380,0.005233,-0.002750,0.005135
1,OA002,OA002,0,0,0,-9,0,0,0,-9,...,-0.005048,-0.001647,-0.004011,-0.001732,-0.001124,-0.000450,-0.004838,0.005386,-0.008734,0.000784
2,OA008,OA008,0,0,0,-9,0,0,0,-9,...,-0.001832,-0.002327,-0.007734,-0.006835,-0.000189,-0.000419,-0.003111,-0.002349,0.002430,0.004818
3,OA009,OA009,0,0,0,-9,0,0,0,-9,...,-0.000380,-0.004055,-0.008628,0.005429,-0.001591,0.000141,0.000035,0.002248,0.001531,0.002027
4,OA010,OA010,0,0,0,-9,0,0,0,-9,...,-0.000336,-0.001688,0.005762,0.003884,-0.003132,-0.001105,0.000151,0.002096,-0.001773,0.000007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,ZQXHNK0329,ZQXHNK0329,0,0,0,-9,0,0,0,-9,...,-0.001857,-0.001227,-0.001137,-0.004659,-0.008839,-0.001791,-0.010866,-0.002626,0.006362,-0.003827
761,ZQXHNK0334,ZQXHNK0334,0,0,0,-9,0,0,0,-9,...,-0.001445,-0.005115,-0.001162,-0.006834,-0.004494,0.005089,0.000161,-0.005366,-0.004125,-0.006292
762,ZQXHNK0341,ZQXHNK0341,0,0,0,-9,0,0,0,-9,...,-0.007181,-0.003043,-0.006757,-0.005861,-0.005582,-0.006700,-0.004138,0.003497,0.009168,0.003166
763,ZQXHNK0343,ZQXHNK0343,0,0,0,-9,0,0,0,-9,...,0.005109,-0.005147,-0.007835,0.000078,-0.004090,-0.001897,0.003561,0.004170,0.002573,-0.007790
764,ZQXHNK0346,ZQXHNK0346,0,0,0,-9,0,0,0,-9,...,0.000085,-0.002824,-0.010073,-0.000022,0.005588,-0.002579,-0.004241,0.007506,0.000657,-0.004116

In [14]:
fam_pheno_pca_covar=fam_pheno_pca #pd.merge(fam_pheno_pca,covar,how='inner')

In [15]:
fam_pheno_pca_covar.drop_duplicates(subset=['#FID','IID'],inplace=True)

In [16]:
fam_pheno_pca_covar

,#FID,IID,FAID,MOID,SEX,PHENO,na1,na2,na3,pheno1,...,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20
0,OA001,OA001,0,0,0,-9,0,0,0,-9,...,0.001640,0.006908,0.003942,0.005487,-0.007080,0.000694,-0.004380,0.005233,-0.002750,0.005135
1,OA002,OA002,0,0,0,-9,0,0,0,-9,...,-0.005048,-0.001647,-0.004011,-0.001732,-0.001124,-0.000450,-0.004838,0.005386,-0.008734,0.000784
2,OA008,OA008,0,0,0,-9,0,0,0,-9,...,-0.001832,-0.002327,-0.007734,-0.006835,-0.000189,-0.000419,-0.003111,-0.002349,0.002430,0.004818
3,OA009,OA009,0,0,0,-9,0,0,0,-9,...,-0.000380,-0.004055,-0.008628,0.005429,-0.001591,0.000141,0.000035,0.002248,0.001531,0.002027
4,OA010,OA010,0,0,0,-9,0,0,0,-9,...,-0.000336,-0.001688,0.005762,0.003884,-0.003132,-0.001105,0.000151,0.002096,-0.001773,0.000007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,ZQXHNK0329,ZQXHNK0329,0,0,0,-9,0,0,0,-9,...,-0.001857,-0.001227,-0.001137,-0.004659,-0.008839,-0.001791,-0.010866,-0.002626,0.006362,-0.003827
761,ZQXHNK0334,ZQXHNK0334,0,0,0,-9,0,0,0,-9,...,-0.001445,-0.005115,-0.001162,-0.006834,-0.004494,0.005089,0.000161,-0.005366,-0.004125,-0.006292
762,ZQXHNK0341,ZQXHNK0341,0,0,0,-9,0,0,0,-9,...,-0.007181,-0.003043,-0.006757,-0.005861,-0.005582,-0.006700,-0.004138,0.003497,0.009168,0.003166
763,ZQXHNK0343,ZQXHNK0343,0,0,0,-9,0,0,0,-9,...,0.005109,-0.005147,-0.007835,0.000078,-0.004090,-0.001897,0.003561,0.004170,0.002573,-0.007790
764,ZQXHNK0346,ZQXHNK0346,0,0,0,-9,0,0,0,-9,...,0.000085,-0.002824,-0.010073,-0.000022,0.005588,-0.002579,-0.004241,0.007506,0.000657,-0.004116

In [17]:
fam_pheno_pca_covar.outcome.value_counts()

4.50    14
4.53    13
4.30    13
4.60    13
4.83    10
        ..
3.89     1
5.89     1
3.84     1
5.45     1
6.18     1
Name: outcome, Length: 231, dtype: int64

In [19]:
fam_pheno_pca_covar.outcome.value_counts()

4.50    14
4.53    13
4.30    13
4.60    13
4.83    10
        ..
3.89     1
5.89     1
3.84     1
5.45     1
6.18     1
Name: outcome, Length: 231, dtype: int64

In [20]:
msg_all=fam_pheno_pca_covar.fillna(-9)

In [21]:
msg_all['Health']=msg_all['IID'].apply(lambda x: 1 if "JK" in x else 0)

In [22]:
msg_all['Health'].value_counts()

0    465
1    300
Name: Health, dtype: int64

In [23]:
msg_all.set_index(keys=["#FID",'IID'],inplace=True)

In [24]:
pheno=msg_all.loc[:,['outcome']]

In [25]:
#pheno['outcome']=pheno['outcome'].astype('int')
pheno

                       outcome
#FID       IID
OA001      OA001          4.80
OA002      OA002          4.20
OA008      OA008          5.40
OA009      OA009          5.00
OA010      OA010          6.80
...                        ...
ZQXHNK0329 ZQXHNK0329     4.48
ZQXHNK0334 ZQXHNK0334     5.22
ZQXHNK0341 ZQXHNK0341     5.44
ZQXHNK0343 ZQXHNK0343     4.41
ZQXHNK0346 ZQXHNK0346     5.11

[765 rows x 1 columns]

In [26]:
pheno.outcome.value_counts()

4.50    14
4.53    13
4.30    13
4.60    13
4.83    10
        ..
3.89     1
5.89     1
3.84     1
5.45     1
6.18     1
Name: outcome, Length: 231, dtype: int64

In [27]:
all(pheno['outcome']==msg_all['outcome'])

True

In [28]:
pheno.reset_index().to_csv('pheno.txt',index=None,header=None,sep='\t')

In [29]:
msg_all

,,FAID,MOID,SEX,PHENO,na1,na2,na3,pheno1,sex_m1f2,age,...,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20,Health
#FID,IID,,,,,,,,,,,,,,,,,,,,,
OA001,OA001,0,0,0,-9,0,0,0,-9,2.0,75.0,...,0.006908,0.003942,0.005487,-0.007080,0.000694,-0.004380,0.005233,-0.002750,0.005135,0
OA002,OA002,0,0,0,-9,0,0,0,-9,2.0,72.0,...,-0.001647,-0.004011,-0.001732,-0.001124,-0.000450,-0.004838,0.005386,-0.008734,0.000784,0
OA008,OA008,0,0,0,-9,0,0,0,-9,2.0,75.0,...,-0.002327,-0.007734,-0.006835,-0.000189,-0.000419,-0.003111,-0.002349,0.002430,0.004818,0
OA009,OA009,0,0,0,-9,0,0,0,-9,2.0,69.0,...,-0.004055,-0.008628,0.005429,-0.001591,0.000141,0.000035,0.002248,0.001531,0.002027,0
OA010,OA010,0,0,0,-9,0,0,0,-9,1.0,65.0,...,-0.001688,0.005762,0.003884,-0.003132,-0.001105,0.000151,0.002096,-0.001773,0.000007,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZQXHNK0329,ZQXHNK0329,0,0,0,-9,0,0,0,-9,2.0,52.0,...,-0.001227,-0.001137,-0.004659,-0.008839,-0.001791,-0.010866,-0.002626,0.006362,-0.003827,0
ZQXHNK0334,ZQXHNK0334,0,0,0,-9,0,0,0,-9,2.0,62.0,...,-0.005115,-0.001162,-0.006834,-0.004494,0.005089,0.000161,-0.005366,-0.004125,-0.006292,0
ZQXHNK0341,ZQXHNK0341,0,0,0,-9,0,0,0,-9,2.0,63.0,...,-0.003043,-0.006757,-0.005861,-0.005582,-0.006700,-0.004138,0.003497,0.009168,0.003166,0
ZQXHNK0343,ZQXHNK0343,0,0,0,-9,0,0,0,-9,1.0,27.0,...,-0.005147,-0.007835,0.000078,-0.004090,-0.001897,0.003561,0.004170,0.002573,-0.007790,0
ZQXHNK0346,ZQXHNK0346,0,0,0,-9,0,0,0,-9,1.0,69.0,...,-0.002824,-0.010073,-0.000022,0.005588,-0.002579,-0.004241,0.007506,0.000657,-0.004116,0

In [30]:
msg_all['age2']=msg_all['age']**2
msg_all['age*sex']=msg_all['age']*msg_all['sex_m1f2']
msg_all['age2*sex']=msg_all['age2']*msg_all['sex_m1f2']

In [31]:
pc_covar=msg_all.loc[:,'PC1':'PC20']
other_qc_covar=msg_all.loc[:,['age']]
qc_covar=pd.concat([pc_covar,other_qc_covar],axis=1)

In [32]:
qc_covar

,,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,...,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20,age
#FID,IID,,,,,,,,,,,,,,,,,,,,,
OA001,OA001,-0.005110,-0.075273,0.002847,-0.003633,-0.015303,0.004142,-0.004056,-0.006482,0.003116,-0.003606,...,0.006908,0.003942,0.005487,-0.007080,0.000694,-0.004380,0.005233,-0.002750,0.005135,75.0
OA002,OA002,0.004636,0.039610,0.007681,0.000456,0.005313,0.005024,0.005047,-0.004748,-0.004883,0.004664,...,-0.001647,-0.004011,-0.001732,-0.001124,-0.000450,-0.004838,0.005386,-0.008734,0.000784,72.0
OA008,OA008,0.002710,0.020468,-0.000528,-0.007886,0.004988,-0.001317,0.008726,-0.002426,0.000593,-0.006717,...,-0.002327,-0.007734,-0.006835,-0.000189,-0.000419,-0.003111,-0.002349,0.002430,0.004818,75.0
OA009,OA009,0.002150,0.024671,0.007874,-0.001271,0.000820,0.005687,0.009856,0.003290,-0.000688,-0.001587,...,-0.004055,-0.008628,0.005429,-0.001591,0.000141,0.000035,0.002248,0.001531,0.002027,69.0
OA010,OA010,0.003949,0.049710,0.011114,0.004493,0.002675,-0.004377,0.007403,-0.004133,-0.001360,0.003092,...,-0.001688,0.005762,0.003884,-0.003132,-0.001105,0.000151,0.002096,-0.001773,0.000007,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZQXHNK0329,ZQXHNK0329,0.001817,0.007929,0.000623,-0.001972,-0.005021,0.004964,-0.000745,-0.000781,-0.000190,0.005715,...,-0.001227,-0.001137,-0.004659,-0.008839,-0.001791,-0.010866,-0.002626,0.006362,-0.003827,52.0
ZQXHNK0334,ZQXHNK0334,0.006053,0.048466,0.010300,-0.001410,0.007228,-0.000127,0.003765,0.001705,-0.001307,0.000107,...,-0.005115,-0.001162,-0.006834,-0.004494,0.005089,0.000161,-0.005366,-0.004125,-0.006292,62.0
ZQXHNK0341,ZQXHNK0341,0.005623,0.060356,0.015468,0.002718,0.008372,0.001315,0.012532,0.002393,-0.005260,-0.003583,...,-0.003043,-0.006757,-0.005861,-0.005582,-0.006700,-0.004138,0.003497,0.009168,0.003166,63.0
ZQXHNK0343,ZQXHNK0343,0.001495,-0.011315,0.000913,0.005015,0.002569,0.007969,0.000642,-0.002775,0.003373,-0.005536,...,-0.005147,-0.007835,0.000078,-0.004090,-0.001897,0.003561,0.004170,0.002573,-0.007790,27.0
ZQXHNK0346,ZQXHNK0346,-0.000411,-0.028707,0.000570,-0.005716,-0.008996,0.007980,0.003957,-0.005817,-0.002039,-0.003355,...,-0.002824,-0.010073,-0.000022,0.005588,-0.002579,-0.004241,0.007506,0.000657,-0.004116,69.0

In [33]:
qc_covar.reset_index().to_csv('qc_covar.txt',index=None,header=None,sep='\t')

In [34]:
msg_all.Health.value_counts()

0    465
1    300
Name: Health, dtype: int64

In [35]:
bin_covar=msg_all.loc[:,['sex_m1f2']]#,'Health'
bin_covar['sex_m1f2']=bin_covar['sex_m1f2'].astype('int')
bin_covar

                       sex_m1f2
#FID       IID
OA001      OA001              2
OA002      OA002              2
OA008      OA008              2
OA009      OA009              2
OA010      OA010              1
...                         ...
ZQXHNK0329 ZQXHNK0329         2
ZQXHNK0334 ZQXHNK0334         2
ZQXHNK0341 ZQXHNK0341         2
ZQXHNK0343 ZQXHNK0343         1
ZQXHNK0346 ZQXHNK0346         1

[765 rows x 1 columns]

In [36]:
bin_covar.reset_index().to_csv('bin_covar.txt',index=None,header=None,sep='\t')